import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Narbar from './components/Narbar'
import { ThemeProvider } from "./components/theme-provider"
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "T-Team",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >  
              {children}
              <Footer />
          </ThemeProvider>
      </body>
    </html>
  );
}
