import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Narbar from './component/Narbar'
import { ThemeProvider } from "./component/theme-provider"
import Footer from "./component/Footer";
import ChatBot from "./component/ChatBot";

export const metadata: Metadata = {
  title: "T-Team",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
       <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >  
              {children}
              <Footer />
              <ChatBot />
          </ThemeProvider>
      </body>
    </html>
  );
}
